site_name: track-reid

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/moon-waning-crescent
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - mkdocstrings
  - search

nav:
  - Home: index.md
  - Source code: code.md
