name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          make download-poetry
      - name: Install requirements
        run: |
          make install
      - name: Deploying MkDocs documentation
        run: |
          poetry run mkdocs build
          poetry run mkdocs gh-deploy --force
